### ISSUE TITLE
zsh completion broken on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by marcov** [openSUSE/scout#13]
I'm on openSUSE Tumbleweed 20180911, and on my system `/usr/bin/python` is still linked to python 2.
```
$ rpm -q --whatprovides /usr/bin/python
python-base-2.7.15-1.3.x86_64
```
So what is happening is that the bash/zsh handlers are running python 3 code with python 2:
https://github.com/openSUSE/scout/blob/59519f80f540d0653c010aa18bbc3cb51cced646/handlers/bin/command_not_found_zsh#L9

Considering that `command_not_found` has the shebang correctly set, you can just call it without using the python interpreter.

**Comment by aplanas** [comment]
Thanks, I see the problem.

Do you want to submit a patch? Your analysis seems very on the spot.

**Comment by marcov** [comment]
Sure!
